### ISSUE TITLE
abs() does not return a new matrix, modifies existing object

### ISSUE THREAD

**Issue by antonkatz** [mljs/matrix#97]
I ran into an interesting bug, where calling `.abs()` on a matrix modified it rather than returning a new matrix. Maybe this should be documented better.

**Comment by antonkatz** [comment]
This is also a problem with `.mul()`.
I think it's reasonable to expect that the operation does not modify the original matrix, and simply returns a new one

**Comment by targos** [comment]
It is by design, to make it possible to chain operations without creating too many intermediate matrices in memory.

Generally, methods that operate on each element of the matrix, like `matrixInstance.mul(2)` do an in-place update (except for methods like `mmul` that can return a matrix with a different size).
Most of these methods are also available statically on the Matrix constructor and return a new matrix.

Example:

```js
const { Matrix } = require('ml-matrix')

const mat = Matrix.ones(4, 6);
mat.mul(2) // in-place update

const otherMat = Matrix.mul(mat, 2) // returns a new matrix
```
